### ISSUE TITLE
Error while loading shared libraries: libnss3.so

### ISSUE THREAD

**Issue by gkiely** [styfle/screenshot-v2#2]
Steps to reproduce
1. Clone the repo
2. `now`
3. See following error

![image](https://user-images.githubusercontent.com/1948935/72688377-5b1acd80-3abb-11ea-8229-8c9d72e11d40.png)

**Comment by gkiely** [comment]
Updating dependencies fixes the above.
```json
"dependencies": {
  "chrome-aws-lambda": "^2.0.2",
  "puppeteer-core": "^2.0.0"
}
```

**Comment by styfle** [comment]
This repo is not maintained. 

For an up-to-date example, see https://github.com/zeit/og-image
